### ISSUE TITLE
Concurrent modification server crash after PR #8

### ISSUE THREAD

**Issue by Cervator** [Terasology/Health#9]
Probably related to two paths hitting the same map in the regeneration scheduler

Scenario: Server/client hosting a BuilderSampleGameplay world, 2nd client joins. Beat randomly on a few blocks and observe yep they don't regen right now, that's another known issue.

Host beat on 2nd client via fisticuffs for a few seconds, observed regen happen fine for 2nd client.

2nd client beat on host for several more seconds, observed regen starting fine but then crashed the server:

```
21:15:18.188 [main] ERROR o.t.e.e.internal.PojoEntityManager - Adding a component (class org.terasology.logic.health.RegenComponent) over an existing component for entity 31
21:15:18.188 [main] WARN  o.t.logic.health.RegenComponent - Regen added baseRegen
21:15:18.188 [main] WARN  o.t.logic.health.RegenComponent - Regen added baseRegen
21:15:18.241 [main] WARN  o.t.logic.health.RegenComponent - regenerating 3
21:15:18.241 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.util.ConcurrentModificationException: null
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211)
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1247)
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1242)
	at com.google.common.collect.AbstractMapBasedMultimap$Itr.next(AbstractMapBasedMultimap.java:1177)
	at org.terasology.logic.health.RegenAuthoritySystem.regenerate(RegenAuthoritySystem.java:102)
	at org.terasology.logic.health.RegenAuthoritySystem.invokeRegenOperations(RegenAuthoritySystem.java:98)
	at org.terasology.logic.health.RegenAuthoritySystem.update(RegenAuthoritySystem.java:70)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:171)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:458)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:397)
	at org.terasology.engine.Terasology.main(Terasology.java:156)
21:15:18.241 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
21:15:18.303 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
21:15:18.352 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
21:15:18.363 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Cerv2
21:15:18.365 [main] INFO  o.t.logic.console.ConsoleImpl - [NOTIFICATION] Player "Cerv2" has left the game
21:15:18.365 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Cerv1
21:15:18.366 [main] INFO  o.t.logic.console.ConsoleImpl - [NOTIFICATION] Player "Cerv1" has left the game
21:15:18.366 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
```

Suspect something relatively simple is wrong in scheduler management land :-)

**Comment by e-aakash** [comment]
Solved by https://github.com/Terasology/Health/pull/10
